name: Publish Image to Docker Hub
on: [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Print environment keys
        run: |
          echo "NODE_ENV=${{ secrets.NODE_ENV }}"
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}"
          echo "CLOUDINARY_KEY=${{ secrets.CLOUDINARY_KEY }}"
          echo "CLOUDINARY_SECRET=${{ secrets.CLOUDINARY_SECRET }}"
          echo "MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}"
          echo "DB_URL=${{ secrets.DB_URL }}"
          echo "MONGOOSE_SECRET=${{ secrets.MONGOOSE_SECRET }}"
          echo "CLIENT_URL=${{ secrets.CLIENT_URL }}"
          echo "SERVER_URL=${{ secrets.SERVER_URL }}"
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}"
          echo "CLOUDINARY=${{ secrets.CLOUDINARY }}"

      - name: Create .env file
        run: |
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_KEY=${{ secrets.CLOUDINARY_KEY }}" >> .env
          echo "CLOUDINARY_SECRET=${{ secrets.CLOUDINARY_SECRET }}" >> .env
          echo "MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "MONGOOSE_SECRET=${{ secrets.MONGOOSE_SECRET }}" >> .env
          echo "CLIENT_URL=${{ secrets.CLIENT_URL }}" >> .env
          echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "CLOUDINARY=${{ secrets.CLOUDINARY }}" >> .env

      - name: build
        run: |
          docker build . -t joshlehmandev/outdoorsy:latest

      - name: publish
        run: |
          docker login -u joshlehmandev -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push joshlehmandev/outdoorsy:latest
