name: Publish Image to Docker Hub
on: [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
          envkey_CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          envkey_CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
          envkey_CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
          envkey_MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          envkey_DB_URL: ${{ secrets.DB_URL }}
          envkey_MONGOOSE_SECRET: ${{ secrets.MONGOOSE_SECRET }}
          envkey_CLIENT_URL: ${{ secrets.CLIENT_URL }}
          envkey_SERVER_URL: ${{ secrets.SERVER_URL }}
          envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          envkey_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          envkey_CLOUDINARY: ${{ secrets.CLOUDINARY }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
      - name: build
        run: |
          docker build . -t joshlehmandev/outdoorsy:latest
      - name: publish
        run: |
          docker login -u joshlehmandev -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push joshlehmandev/outdoorsy:latest
